# Generated by Django 5.0.14 on 2026-07-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_subtitle',
            field=models.CharField(blank=True, default='Mahzarat Store designs everyday clothing for women who refuse to choose between comfort and presence.', max_length=300),
        ),
    ]
